// Obfuscated config
const _x=['edutrack-admin','firebaseapp','AIzaSyAFpwi3k7Qth9MiqqRGKstY0Zkj_vrcdFY','193864081571','1:193864081571:web:7501afde01291f81e61f16','com','storage','app'];
const _c={a:_x[2],b:_x[0]+'.'+_x[1]+'.'+_x[5],c:_x[0],d:_x[0]+'.'+_x[1]+_x[6]+'.'+_x[7],e:_x[3],f:_x[4]};
firebase.initializeApp({apiKey:_c.a,authDomain:_c.b,projectId:_c.c,storageBucket:_c.d,messagingSenderId:_c.e,appId:_c.f});

const _db=firebase.firestore();
const _rc=document.getElementById('report-content');

async function _load(){const params=new URLSearchParams(window.location.search);const tid=params.get('testId'),sid=params.get('studentId');if(!tid||!sid){_rc.innerHTML='<div class="alert alert-danger">Invalid report link</div>';return}try{const[test,result,student]=await Promise.all([_db.collection('tests').doc(tid).get(),_db.collection('results').where('testId','==',tid).where('studentId','==',sid).limit(1).get(),_db.collection('students').doc(sid).get()]);if(!test.exists||result.empty||!student.exists){_rc.innerHTML='<div class="alert alert-warning">Data not found</div>';return}const td=test.data(),rd=result.docs[0].data(),sd=student.data();_render(td,rd,sd)}catch(e){console.error('Load error:',e);_rc.innerHTML='<div class="alert alert-danger">Error loading report</div>'}}

function _render(test,result,student){const qs=test.questions||[];let correct=0,total=0;let qhtml='';qs.forEach((q,i)=>{const qn=i+1;const uk=`Q${qn}`;const ua=result[uk];total++;const isC=ua==='R';if(isC)correct++;const opts=[q['Option 1'],q['Option 2'],q['Option 3'],q['Option 4']];const ca=parseInt(q['Correct Option'])||0;qhtml+=`<div class="question-item"><div class="d-flex justify-content-between mb-3"><h6 class="fw-bold">Question ${qn}</h6><span class="badge ${isC?'bg-success':'bg-danger'}">${isC?'Correct':'Wrong'}</span></div><p class="mb-3">${q.Question||'No question text'}</p>`;opts.forEach((opt,idx)=>{if(!opt)return;const oi=idx+1;const isCO=oi===ca;const isUA=ua===String(oi);let cls='option-neutral';if(isCO&&isUA)cls='option-correct';else if(isCO)cls='option-correct';else if(isUA)cls='option-wrong';qhtml+=`<div class="option-box ${cls}"><strong>${String.fromCharCode(65+idx)}.</strong> ${opt}${isCO?' ✓':''}${isUA&&!isCO?' ✗':''}</div>`});qhtml+='</div>'});const score=total>0?Math.round(correct/total*100):0;_rc.innerHTML=`<div class="card shadow-sm mb-4"><div class="card-body"><div class="row"><div class="col-md-6"><h5 class="fw-bold mb-3">Student Information</h5><p><strong>Name:</strong> ${student.name||'N/A'}</p><p><strong>Student ID:</strong> ${student.id||result.studentId}</p><p><strong>Phone:</strong> ${student.phone||'N/A'}</p></div><div class="col-md-6"><h5 class="fw-bold mb-3">Test Information</h5><p><strong>Test:</strong> ${test.testName||'N/A'}</p><p><strong>Score:</strong> <span class="badge ${score>=70?'bg-success':'bg-danger'} fs-6">${correct}/${total} (${score}%)</span></p></div></div></div></div><h5 class="fw-bold mb-3">Detailed Results</h5>${qhtml}`}

_load();
